import { BrandSeal } from "@/components/full-report-v2/brand-seal";
import { ModuleWheel } from "@/components/full-report-v2/module-wheel";
import { ReportPage } from "@/components/full-report-v2/report-page";
import { MODULE_INCLUDES_LIST } from "@/lib/full-report-v2/module-wheel";
import type { FullReportV2Payload } from "@/lib/full-report-v2/types";

type Page00CoverProps = {
  payload: FullReportV2Payload;
};

export function Page00Cover({ payload }: Page00CoverProps) {
  const { client, report, calculation } = payload;
  const sigCodes = [
    calculation.s1.code,
    calculation.s3.code,
    calculation.s2.code,
    calculation.s0.code,
  ].join(" | ");

  const sigSub = [
    `${calculation.s1.code} ${calculation.s1.title}`,
    `${calculation.s3.code} ${calculation.s3.title}`,
    `${calculation.s2.code} ${calculation.s2.title}`,
    `${calculation.s0.code} ${calculation.s0.title}`,
  ].join(" | ");

  return (
    <ReportPage sectionId="page-00-cover" className="fr-v2-cover-page">
      <div className="fr-v2-cosmic-lines" />
      <section className="fr-v2-cover-grid">
        <section className="fr-v2-cover-left">
          <BrandSeal size={82} className="fr-v2-cover-seal" />
          <div className="fr-v2-cover-kicker">FULL</div>
          <div className="fr-v2-cover-number">1320</div>
          <div className="fr-v2-cover-title">
            Soul Origin
            <br />
            Report
          </div>
          <div className="fr-v2-gold-divider" />
          <p className="fr-v2-cover-description">
            A complete soul mapping across 10 core dimensions — revealing your origin,
            pattern, purpose, and path.
          </p>
          <div className="fr-v2-mirror-line">Your code is a mirror — not a sentence.</div>
          <div className="fr-v2-fate-line">
            Not your fate.
            <br />
            Your mirror.
          </div>
        </section>

        <section className="fr-v2-cover-center">
          <ModuleWheel />
          <div className="fr-v2-signature-panel">
            <span className="fr-v2-signature-icon fr-v2-signature-icon--left" aria-hidden="true">
              <BrandSeal size={44} />
            </span>
            <div className="fr-v2-signature-body">
              <div className="fr-v2-signature-label">Your Core Signature Preview</div>
              <div className="fr-v2-signature-code">{sigCodes}</div>
              <div className="fr-v2-signature-sub">{sigSub}</div>
            </div>
            <span className="fr-v2-signature-icon fr-v2-signature-icon--right" aria-hidden="true">
              ✦
            </span>
          </div>
        </section>

        <section className="fr-v2-cover-right">
          <aside className="fr-v2-client-card">
            <div className="fr-v2-card-title">Prepared For</div>
            <div className="fr-v2-info-row">
              <div className="fr-v2-info-icon">♙</div>
              <div>
                <div className="fr-v2-info-label">Name</div>
                <div className="fr-v2-info-value">{client.name}</div>
              </div>
            </div>
            <div className="fr-v2-info-row">
              <div className="fr-v2-info-icon">□</div>
              <div>
                <div className="fr-v2-info-label">Birth Date</div>
                <div className="fr-v2-info-value">{client.birth_date_display}</div>
              </div>
            </div>
            <div className="fr-v2-info-row">
              <div className="fr-v2-info-icon">☷</div>
              <div>
                <div className="fr-v2-info-label">Report Type</div>
                <div className="fr-v2-info-value">{report.type}</div>
              </div>
            </div>
            <div className="fr-v2-info-row">
              <div className="fr-v2-info-icon">◎</div>
              <div>
                <div className="fr-v2-info-label">Generated By</div>
                <div className="fr-v2-info-value">{report.generated_by}</div>
              </div>
            </div>
            <div className="fr-v2-info-row">
              <div className="fr-v2-info-icon">☉</div>
              <div>
                <div className="fr-v2-info-label">Report Version</div>
                <div className="fr-v2-info-value">{report.version}</div>
              </div>
            </div>
            <div className="fr-v2-info-row">
              <div className="fr-v2-info-icon">◷</div>
              <div>
                <div className="fr-v2-info-label">Generated On</div>
                <div className="fr-v2-info-value">
                  {report.generated_date} · {report.generated_time}
                </div>
              </div>
            </div>
          </aside>

          <aside className="fr-v2-includes-card">
            <div className="fr-v2-card-title">This Full Report Includes</div>
            <div className="fr-v2-includes-badges">
              {MODULE_INCLUDES_LIST.map((item) => (
                <span
                  key={item.code}
                  className="fr-v2-includes-badge"
                  title={`${item.code} ${item.label}`}
                >
                  {item.code}
                </span>
              ))}
            </div>
            <div className="fr-v2-includes-caption">
              10 Core Modules · Complete Soul Map
            </div>
          </aside>
        </section>

        <footer className="fr-v2-cover-footer">
          <div className="fr-v2-cover-footer-symbol">◇</div>
          <div className="fr-v2-cover-footer-text">
            <strong>Disclaimer:</strong>
            <br />
            This report is a symbolic self-reflection tool designed for clarity, insight,
            and personal growth. It is not a substitute for professional advice, diagnosis,
            therapy, legal counsel, financial advice, or treatment.
          </div>
          <div className="fr-v2-cover-footer-agency">
            You remain the author of your life.
            <br />
            Use this report as a mirror for awareness, not as a fixed identity or absolute
            truth.
          </div>
        </footer>
      </section>
    </ReportPage>
  );
}
